### ISSUE TITLE
Corral crashing when thread id is bv32

### ISSUE THREAD

**Issue by zvonimir** [boogie-org/corral#109]
This is the offending bpl file: [pero.zip](https://github.com/boogie-org/corral/files/4221048/pero.zip)

This is how I run Corral:
```
corral pero.bpl /tryCTrace /noTraceOnDisk /printDataValues:1 /k:2 /useProverEvaluate /timeLimit:1200 /cex:1 /maxStaticLoopBound:1 /recursionBound:1 /bopt:proverOpt:OPTIMIZE_FOR_BV=true /bopt:boolControlVC
```
I can see in the source code that Corral attempts to figure out whether to use int or bv32, but for some reason this does not do the right thing. And I don't have the development environment set up on my machine to be able to quickly debug this, and so I am hoping someone else could jump in and take a look.

**Comment by zvonimir** [comment]
@akashlal Given that you I guess kind of reloaded Corral into your brain, maybe this would be a quick fix :). Thanks!

**Comment by zvonimir** [comment]
@akashlal Any chance you could quickly take a look at this one?
To reproduce it, you should use the following command on the Boogie file attached above:
```
corral pero.bpl /tryCTrace /noTraceOnDisk /printDataValues:1 /k:2 /useProverEvaluate /timeLimit:1200 /cex:1 /maxStaticLoopBound:1 /recursionBound:1
```
Thanks!
FYI, this is related to some pthreads benchmarks that Amazon is interested in.

**Comment by akashlal** [comment]
Apologies for the delay. I'm looking at this now. It seems that Corral does find the right type (bv32) but then forgets somehow. I'll report back when I have something. I can think of one workaround. Instead of:
```
procedure  corral_getThreadID() returns (x:bv32);
```
Let this guy return `int`. Then introduce another procedure:
```
function f(a: int) : bv32; 
axiom (forall a1: int, a2:int :: f(a1) == f(a2) ==> a1 == a2);
 
procedure smack_getThreadID returns (x: bv32) {
   var tid: int;
   call tid := corral_getThreadID();
   x := f(tid);
}
```

I suppose you can use the built-in `int2bv32` instead of `f` but I don't know what axioms it invokes internally. You just need `f` to be onto.

Anyway, I'll see if I can figure this out. Very happy to see corral applied to a concurrent program!
