### ISSUE TITLE
Use of axioms in corral

### ISSUE THREAD

**Issue by prgantonino** [boogie-org/corral#99]
I am trying to model an enumeration in Boogie and get corral to verify that a value of this enumeration is within the list of its values but I am getting an assertion error. 
I even went as far as adding the axiom as an assume within the main procedure but I still get the error.

Is there some fundamental issue with axioms in corral that I am missing?

Thank you very much!

Here is the code:

type ABC;
const unique A : ABC;
const unique B : ABC;
const unique C : ABC;
axiom (forall e : ABC :: e == A || e == B || e == C);

procedure boogie_si_recordi (i : int) returns ();
procedure boogie_si_recordabc (st : ABC) returns ();

procedure main ($this : int) returns ()
{

    var abc : ABC;
    assume (forall e : ABC :: e == A || e == B || e == C);

    call boogie_si_recordabc(A);
    call boogie_si_recordabc(B);
    call boogie_si_recordabc(C);
    call boogie_si_recordi(0);
    call boogie_si_recordabc(abc);

    assert (abc == A || abc == B || abc == C);

}

**Comment by RustanLeino** [comment]
To do what you're trying to do, change the axiom to a definition of a predicate.

    function IsABC(e: ABC): bool;
    axiom (forall e: ABC :: IsABC(e) <==> e == A || e == B || e == C);

Think of `ABC` as a type that contains `A`, `B`, and `C` and potentially lots of other values as well. The `IsABC` predicate identifies those `ABC` values that you intend to use.

You'll need to thread the `IsABC` predicate through your program, so that Boogie knows which variables of type `ABC` hold the intended values. It will probably be convenient to do this in `where` clauses (see the Boogie Language Reference manual, "This is Boogie 2").

The reason your attempt above doesn't work has to do with _matching triggers_. Perhaps the following FAQ for Dafny is also helpful for you in Boogie:
https://github.com/dafny-lang/dafny/wiki/FAQ#how-does-dafny-handle-quantifiers-ive-heard-about-triggers-what-are-those

  Rustan

**Comment by prgantonino** [comment]
Thank you! 

Just a follow up question, could the type ABC be used as a trigger so boogie/corral would automatically instantiate a quantifier for variables of this type?

Is there some theoretical reason not to have this type of triggering? Or is it more a matter of a design choice for the implementation of boogie/corral?

Thank you again,

Pedro
